apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: reverseproxy